name: time-series-env
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - pytest
  - flake8
  - pyyaml
  - pip
  - pip:
      - fbprophet
